DROP TABLE IF EXISTS Student;

DROP TABLE IF EXISTS Class;

DROP TABLE IF EXISTS Dept;

DROP TABLE IF EXISTS Association;

CREATE TABLE Dept(
  Dno VARCHAR(10) PRIMARY KEY,
  Dname VARCHAR(20),
  Daddr VARCHAR(40)
);

CREATE TABLE Student(
  Sno VARCHAR(11) PRIMARY KEY,
  Sname VARCHAR(20),
  Sage INT,
  Dno VARCHAR(10),
  Sclass VARCHAR(20),
  Sdom VARCHAR(20),
  FOREIGN KEY(Dno) REFERENCES Dept(Dno)
);

CREATE TABLE Class(
  Cno VARCHAR(10) PRIMARY KEY,
  Cname VARCHAR(20),
  Cyear VARCHAR(5),
  Dno VARCHAR(10),
  Cnum INT,
  FOREIGN KEY(Dno) REFERENCES Dept(Dno)
);

CREATE TABLE Association(
  Ano VARCHAR(10) PRIMARY KEY,
  Aname VARCHAR(20),
  Ayear VARCHAR(5),
  Aaddr VARCHAR(40)
);

CREATE TABLE Dormitory(
  dormitoryNo VARCHAR(10) PRIMARY KEY,
  dormitoryName VARCHAR(20)
);